import type { Metadata } from "next";
import {Montserrat} from 'next/font/google';
import "./globals.css";
import QueryProvider from "@/providers/query-provider";


const geistSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["100","200","400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Youssefkleeno | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
